<?php
/**
 * Plugin Name: StaffSwap Profiles
 * Description: Member profile fields and profile display shortcode.
 * Version: 1.0.0
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
function staffswap_profile_fields( $user ) { ?><h2>StaffSwap Professional Profile</h2><table class="form-table"><tr><th><label for="staffswap_profession">Profession</label></th><td><input class="regular-text" name="staffswap_profession" id="staffswap_profession" value="<?php echo esc_attr( get_user_meta( $user->ID, 'staffswap_profession', true ) ); ?>"></td></tr><tr><th><label for="staffswap_location">Current location</label></th><td><input class="regular-text" name="staffswap_location" id="staffswap_location" value="<?php echo esc_attr( get_user_meta( $user->ID, 'staffswap_location', true ) ); ?>"></td></tr><tr><th><label for="staffswap_employer">Employer</label></th><td><input class="regular-text" name="staffswap_employer" id="staffswap_employer" value="<?php echo esc_attr( get_user_meta( $user->ID, 'staffswap_employer', true ) ); ?>"></td></tr></table><?php }
add_action( 'show_user_profile', 'staffswap_profile_fields' ); add_action( 'edit_user_profile', 'staffswap_profile_fields' );
function staffswap_save_profile_fields( $user_id ) { if ( ! current_user_can( 'edit_user', $user_id ) ) { return; } foreach ( array( 'profession', 'location', 'employer' ) as $field ) { if ( isset( $_POST['staffswap_' . $field] ) ) { update_user_meta( $user_id, 'staffswap_' . $field, sanitize_text_field( wp_unslash( $_POST['staffswap_' . $field] ) ) ); } } }
add_action( 'personal_options_update', 'staffswap_save_profile_fields' ); add_action( 'edit_user_profile_update', 'staffswap_save_profile_fields' );
function staffswap_profile_shortcode( $atts ) { $atts = shortcode_atts( array( 'user' => get_current_user_id() ), $atts, 'staffswap_profile' ); $user = get_userdata( (int) $atts['user'] ); if ( ! $user ) { return '<div class="panel">Profile not found.</div>'; } ob_start(); ?><article class="panel content-form"><div class="person"><div class="avatar"><?php echo esc_html( strtoupper( substr( $user->display_name, 0, 1 ) ) ); ?></div><div><h1><?php echo esc_html( $user->display_name ); ?></h1><p class="muted"><?php echo esc_html( get_user_meta( $user->ID, 'staffswap_profession', true ) ?: 'StaffSwap member' ); ?></p></div></div><div class="form-grid" style="margin-top:24px"><div><strong>Current location</strong><p class="muted"><?php echo esc_html( get_user_meta( $user->ID, 'staffswap_location', true ) ?: 'Not provided' ); ?></p></div><div><strong>Employer</strong><p class="muted"><?php echo esc_html( get_user_meta( $user->ID, 'staffswap_employer', true ) ?: 'Not provided' ); ?></p></div></div></article><?php return ob_get_clean(); }
add_shortcode( 'staffswap_profile', 'staffswap_profile_shortcode' );