<?php get_footer(); ?>
<?php
get_header();
$hero_title = staffswap_home_setting( 'hero_title', 'Swap Your Workplace. Change Your Life.' );
$hero_text = staffswap_home_setting( 'hero_text', 'Connect with verified professionals across Zambia who want to swap their workplace just like you. Secure, efficient, and professional workplace mobility.' );
$stats = array_map( 'trim', explode( '|', staffswap_home_setting( 'stats', '12,000+|3,200+|150+|10|20+' ) ) );
$stat_labels = array( 'Active professionals', 'Successful swaps', 'Professions', 'Provinces covered', 'Categories' );
?>
<section class="landing-hero"><div class="landing-hero__copy"><p class="eyebrow">WORKPLACE MOBILITY, MADE CLEAR</p><h1><?php echo esc_html( $hero_title ); ?></h1><p><?php echo esc_html( $hero_text ); ?></p><div class="hero-actions"><a class="button button--primary" href="<?php echo esc_url( home_url( '/create-swap/' ) ); ?>"><?php echo esc_html( get_theme_mod( 'staffswap_hero_primary_label', 'Create Swap Post' ) ); ?></a><a class="button button--outline" href="<?php echo esc_url( home_url( '/swaps/' ) ); ?>"><?php echo esc_html( get_theme_mod( 'staffswap_hero_secondary_label', 'Browse Swaps' ) ); ?></a></div><div class="trust-line"><span class="trust-avatars"><i>LM</i><i>BC</i><i>RT</i></span><span>Join 12,000+ professionals who have already found their perfect swap.</span></div></div><div class="swap-visual"><div class="swap-node swap-node--from"><div class="swap-avatar">LM</div><strong>Lusaka</strong><small>General Hospital</small></div><div class="swap-connector"><b>&harr;</b><small>95% MATCH</small></div><div class="swap-node swap-node--to"><div class="swap-avatar swap-avatar--blue">BM</div><strong>Ndola</strong><small>Regional Clinic</small></div></div></section>
<section class="quick-search panel"><div class="field"><label for="hero-current">Current Location</label><input id="hero-current" placeholder="Select province"></div><div class="field"><label for="hero-desired">Desired Location</label><input id="hero-desired" placeholder="Select province"></div><div class="field"><label for="hero-profession">Profession</label><input id="hero-profession" placeholder="Select profession"></div><div class="field"><label for="hero-employer">Employer Type</label><input id="hero-employer" placeholder="All types"></div><a class="button button--primary" href="<?php echo esc_url( home_url( '/search/' ) ); ?>">Search Swaps</a></section>
<section class="how-it-works"><div class="section-heading section-heading--center"><p class="eyebrow">A CLEARER WAY FORWARD</p><h2>How StaffExchangeHub Works</h2></div><div class="steps"><?php $steps = array( array( '01', 'Create Profile', 'Tell us about yourself, your current job and location.' ), array( '02', 'Post Swap Request', 'Add details of where you want to go and why.' ), array( '03', 'Find Matches', 'We find compatible professionals who want to swap.' ), array( '04', 'Connect & Chat', 'Agree on details and communicate securely.' ), array( '05', 'Swap & Succeed', 'Enjoy your new work location and start fresh.' ) ); foreach ( $steps as $step ) : ?><div class="step"><span><?php echo esc_html( $step[0] ); ?></span><h3><?php echo esc_html( $step[1] ); ?></h3><p><?php echo esc_html( $step[2] ); ?></p></div><?php endforeach; ?></div></section>
<section class="featured-section"><div class="section-heading"><div><p class="eyebrow">VERIFIED OPPORTUNITIES</p><h2>Featured Swap Opportunities</h2><p class="muted">Recent verified postings from top professionals</p></div><a class="text-link" href="<?php echo esc_url( home_url( '/swaps/' ) ); ?>">View all listings &rarr;</a></div><div class="featured-grid"><?php if ( function_exists( 'staffswap_listing_card' ) ) : $featured = new WP_Query( array( 'post_type' => 'swap_listing', 'post_status' => 'publish', 'posts_per_page' => 3, 'meta_key' => '_staffswap_verified', 'meta_value' => '1' ) ); if ( $featured->have_posts() ) : while ( $featured->have_posts() ) : $featured->the_post(); echo staffswap_listing_card( get_the_ID() ); endwhile; wp_reset_postdata(); else : ?><div class="featured-card"><span class="featured-avatar">LM</span><strong>Registered Nurse</strong><small>Verified &bull; Lusaka &rarr; Ndola</small><em>95% match</em><a class="button button--primary" href="<?php echo esc_url( home_url( '/register/' ) ); ?>">View Match</a></div><div class="featured-card"><span class="featured-avatar featured-avatar--blue">BC</span><strong>Maths Teacher</strong><small>Verified &bull; Kitwe &rarr; Livingstone</small><em>92% match</em><a class="button button--primary" href="<?php echo esc_url( home_url( '/register/' ) ); ?>">View Match</a></div><div class="featured-card"><span class="featured-avatar featured-avatar--gold">RT</span><strong>Bank Officer</strong><small>Verified &bull; Lusaka &rarr; Kabwe</small><em>90% match</em><a class="button button--primary" href="<?php echo esc_url( home_url( '/register/' ) ); ?>">View Match</a></div><?php endif; else : ?><div class="panel"><h2>Featured swaps are coming soon</h2><p class="muted">Activate StaffSwap Core and publish your first verified listing.</p></div><?php endif; ?></div></section>
<section class="stats-band"><div class="stats-grid"><?php foreach ( $stats as $index => $stat ) : ?><div><strong><?php echo esc_html( $stat ); ?></strong><span><?php echo esc_html( $stat_labels[ $index ] ?? 'Network metric' ); ?></span></div><?php endforeach; ?></div></section>
<section class="landing-bottom"><div class="testimonial panel"><b>99</b><blockquote>&ldquo;StaffExchangeHub made it easy for me to find a swap to Ndola. The process was simple, secure and fast.&rdquo;</blockquote><div class="testimonial-person"><span class="featured-avatar">LM</span><span><strong>Lydia Mwansa</strong><small>Nurse, Ndola<br><span class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</span></small></span></div></div><div class="alert-card"><p class="eyebrow">STAY AHEAD OF THE NEXT MATCH</p><h2>Get Swap Alerts</h2><p>Be the first to know about new matching opportunities in your field and preferred location.</p><form><input type="email" placeholder="Enter your email" aria-label="Email address"><input type="submit" value="Subscribe"></form><small>No spam. Unsubscribe anytime.</small></div></section>
<?php get_footer(); ?>
