<?php
get_header();
if ( staffswap_has_builder_content() ) :
	while ( have_posts() ) : the_post(); the_content(); endwhile;
	get_footer();
	return;
endif;
?>
<section class="page-hero"><p class="eyebrow"><?php echo esc_html__( 'SIMPLE, TRANSPARENT PLANS', 'staffswap' ); ?></p><h1><?php echo esc_html__( 'Choose the visibility that fits your move.', 'staffswap' ); ?></h1><p><?php echo esc_html__( 'Start free, build trusted connections, and unlock more reach when your workplace exchange needs it.', 'staffswap' ); ?></p></section>
<section class="pricing-grid"><article class="pricing-card"><p class="eyebrow">STARTER</p><h2>Free</h2><p class="pricing-price">ZMW 0 <small>/ forever</small></p><ul><li>Create your professional profile</li><li>Browse verified listings</li><li>Receive compatible matches</li></ul><a class="button button--outline" href="<?php echo esc_url( home_url( '/register/' ) ); ?>">Get started</a></article><article class="pricing-card pricing-card--featured"><span class="pricing-badge">MOST POPULAR</span><p class="eyebrow">PROFESSIONAL</p><h2>Plus</h2><p class="pricing-price">ZMW 99 <small>/ month</small></p><ul><li>Everything in Starter</li><li>Priority match visibility</li><li>Unlimited saved searches</li></ul><a class="button button--primary" href="<?php echo esc_url( home_url( '/register/' ) ); ?>">Choose Plus</a></article><article class="pricing-card"><p class="eyebrow">INSTITUTION</p><h2>Partner</h2><p class="pricing-price">Talk to us</p><ul><li>Team and institution profiles</li><li>Featured workforce opportunities</li><li>Dedicated support</li></ul><a class="button button--outline" href="mailto:hello@staffexchangehub.com">Contact team</a></article></section>
<section class="faq-section"><div class="section-heading section-heading--center"><p class="eyebrow">NEED TO KNOW</p><h2>Frequently Asked Questions</h2></div><div class="faq-grid"><details open><summary>Is StaffExchangeHub free to join?</summary><p>Yes. You can create a profile, browse listings, and explore the network for free.</p></details><details><summary>How are listings verified?</summary><p>Listings are reviewed before publication, with verification status shown clearly on each profile.</p></details><details><summary>Can institutions join?</summary><p>Yes. Partner plans support institutions managing professional mobility at scale.</p></details></div></section>
<?php get_footer(); ?>
