<?php
get_header();
if ( staffswap_has_builder_content() ) :
	while ( have_posts() ) : the_post(); the_content(); endwhile;
	get_footer();
	return;
endif;
?>
<section class="page-hero"><p class="eyebrow"><?php echo esc_html__( 'SIMPLE, TRANSPARENT PLANS', 'staffswap' ); ?></p><h1><?php echo esc_html__( 'Choose the visibility that fits your move.', 'staffswap' ); ?></h1><p><?php echo esc_html__( 'Start free, build trusted connections, and unlock more reach when your workplace exchange needs it.', 'staffswap' ); ?></p></section>
<section class="pricing-grid"><article class="pricing-card"><p class="eyebrow">VIP GOLD</p><h2>1 Month</h2><p class="pricing-price">ZMW 99 <small>/ month</small></p><ul><li>Priority match visibility</li><li>Direct contact access</li><li>Official transfer letters</li></ul><?php echo shortcode_exists( 'staffswap_upgrade' ) ? do_shortcode( '[staffswap_upgrade plan="month"]' ) : ''; ?></article><article class="pricing-card pricing-card--featured"><span class="pricing-badge">BEST VALUE</span><p class="eyebrow">VIP GOLD</p><h2>3 Months</h2><p class="pricing-price">ZMW 249 <small>/ 3 months</small></p><ul><li>Everything in VIP Gold</li><li>Priority national placement</li><li>Unlimited transfer letters</li></ul><?php echo shortcode_exists( 'staffswap_upgrade' ) ? do_shortcode( '[staffswap_upgrade plan="quarter"]' ) : ''; ?></article><article class="pricing-card"><p class="eyebrow">VIP GOLD</p><h2>Lifetime</h2><p class="pricing-price">ZMW 799 <small>/ once</small></p><ul><li>Lifetime VIP access</li><li>Permanent priority placement</li><li>Full document hub access</li></ul><?php echo shortcode_exists( 'staffswap_upgrade' ) ? do_shortcode( '[staffswap_upgrade plan="lifetime"]' ) : ''; ?></article></section>
<section class="faq-section"><div class="section-heading section-heading--center"><p class="eyebrow">NEED TO KNOW</p><h2>Frequently Asked Questions</h2></div><div class="faq-grid"><details open><summary>Is StaffExchangeHub free to join?</summary><p>Yes. You can create a profile, browse listings, and explore the network for free.</p></details><details><summary>How are listings verified?</summary><p>Listings are reviewed before publication, with verification status shown clearly on each profile.</p></details><details><summary>Can institutions join?</summary><p>Yes. Partner plans support institutions managing professional mobility at scale.</p></details></div></section>
<?php get_footer(); ?>
