<?php
/**
 * Plugin Name: StaffSwap Resources
 * Description: Resource centre content, categories, downloads, and search.
 * Version: 1.0.0
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
function staffswap_resources_post_type() { register_post_type( 'staff_resource', array( 'labels' => array( 'name' => 'Resources', 'singular_name' => 'Resource' ), 'public' => true, 'show_in_rest' => true, 'menu_icon' => 'dashicons-media-document', 'supports' => array( 'title', 'editor', 'thumbnail' ), 'rewrite' => array( 'slug' => 'resource' ) ) ); register_taxonomy( 'resource_category', 'staff_resource', array( 'label' => 'Resource Categories', 'public' => true, 'show_in_rest' => true, 'hierarchical' => true, 'rewrite' => array( 'slug' => 'resource-category' ) ) ); }
add_action( 'init', 'staffswap_resources_post_type' );
register_activation_hook( __FILE__, function() { staffswap_resources_post_type(); flush_rewrite_rules(); } );
register_deactivation_hook( __FILE__, 'flush_rewrite_rules' );
function staffswap_resources_shortcode() { $search = isset( $_GET['resource_search'] ) ? sanitize_text_field( wp_unslash( $_GET['resource_search'] ) ) : ''; $query = new WP_Query( array( 'post_type' => 'staff_resource', 'post_status' => 'publish', 'posts_per_page' => 12, 's' => $search ) ); ob_start(); ?>
<section class="resource-hero"><div><p class="eyebrow">STAFFEXCHANGEHUB LIBRARY</p><h1>Resources Centre</h1><p class="muted">Free guides, templates, policies, forms, and career resources for professionals in healthcare, education, and beyond.</p><form class="resource-search" method="get"><input name="resource_search" value="<?php echo esc_attr( $search ); ?>" placeholder="Search resources, templates, guides..."><input type="submit" value="Search"></form><div class="resource-stats"><div class="resource-stat"><strong>12,500+</strong><span class="muted">Downloads</span></div><div class="resource-stat"><strong><?php echo esc_html( $query->found_posts ); ?>+</strong><span class="muted">Resources</span></div><div class="resource-stat"><strong>20+</strong><span class="muted">Professions</span></div></div></div></section><section><div class="page-heading"><div><p class="eyebrow">BROWSE BY CATEGORY</p><h2>Find what you need</h2></div></div><div class="resource-categories"><?php $categories = get_terms( array( 'taxonomy' => 'resource_category', 'hide_empty' => false, 'number' => 5 ) ); if ( ! is_wp_error( $categories ) ) : foreach ( $categories as $category ) : ?><a class="resource-card" href="<?php echo esc_url( get_term_link( $category ) ); ?>"><h3><?php echo esc_html( $category->name ); ?></h3><p><?php echo esc_html( $category->count ); ?> resources</p></a><?php endforeach; endif; ?></div></section><section style="margin-top:48px"><div class="page-heading"><div><p class="eyebrow">POPULAR RESOURCES</p><h2>Practical tools for your next move</h2></div></div><div class="resource-grid"><?php if ( $query->have_posts() ) : while ( $query->have_posts() ) : $query->the_post(); ?><article class="resource-card"><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html( wp_trim_words( get_the_excerpt(), 18 ) ); ?></p><a class="resource-link" href="<?php the_permalink(); ?>">View resource <span aria-hidden="true">&#8594;</span></a></article><?php endwhile; wp_reset_postdata(); else : ?><div class="panel"><h2>No resources found</h2><p class="muted">Try another search term.</p></div><?php endif; ?></div></section>
<?php return ob_get_clean(); }
add_shortcode( 'staffswap_resources', 'staffswap_resources_shortcode' );