<?php
/**
 * Plugin Name: StaffSwap Resources
 * Description: Resource centre content, categories, downloads, and search.
 * Version: 1.0.0
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
function staffswap_resources_post_type() { register_post_type( 'staff_resource', array( 'labels' => array( 'name' => 'Resources', 'singular_name' => 'Resource' ), 'public' => true, 'show_in_rest' => true, 'menu_icon' => 'dashicons-media-document', 'supports' => array( 'title', 'editor', 'thumbnail' ), 'rewrite' => array( 'slug' => 'resource' ) ) ); register_taxonomy( 'resource_category', 'staff_resource', array( 'label' => 'Resource Categories', 'public' => true, 'show_in_rest' => true, 'hierarchical' => true, 'rewrite' => array( 'slug' => 'resource-category' ) ) ); }
add_action( 'init', 'staffswap_resources_post_type' );
register_activation_hook( __FILE__, function() { staffswap_resources_post_type(); flush_rewrite_rules(); } );
register_deactivation_hook( __FILE__, 'flush_rewrite_rules' );
function staffswap_resources_shortcode() {
	$search = isset( $_GET['resource_search'] ) ? sanitize_text_field( wp_unslash( $_GET['resource_search'] ) ) : '';
	$category_slug = isset( $_GET['resource_category'] ) ? sanitize_title( wp_unslash( $_GET['resource_category'] ) ) : '';
	$query_args = array( 'post_type' => 'staff_resource', 'post_status' => 'publish', 'posts_per_page' => 12, 's' => $search );
	if ( $category_slug ) { $query_args['tax_query'] = array( array( 'taxonomy' => 'resource_category', 'field' => 'slug', 'terms' => $category_slug ) ); }
	$query = new WP_Query( $query_args );
	global $wpdb;
	$total_downloads = (int) $wpdb->get_var( "SELECT SUM(CAST(meta_value AS UNSIGNED)) FROM {$wpdb->postmeta} pm INNER JOIN {$wpdb->posts} p ON p.ID = pm.post_id WHERE pm.meta_key = '_staffswap_download_count' AND p.post_type = 'staff_resource' AND p.post_status = 'publish'" );
	$all_categories = get_terms( array( 'taxonomy' => 'resource_category', 'hide_empty' => false ) );
	$category_count = ! is_wp_error( $all_categories ) ? count( $all_categories ) : 0;
	ob_start(); ?>
<section class="resource-hero"><div><p class="eyebrow">STAFFEXCHANGEHUB LIBRARY</p><h1>Resources Centre</h1><p class="muted">Free guides, templates, policies, forms, and career resources for professionals in healthcare, education, and beyond.</p><form class="resource-search" method="get"><input name="resource_search" value="<?php echo esc_attr( $search ); ?>" placeholder="Search resources, templates, guides..."><select name="resource_category" aria-label="Filter by category"><option value="">All categories</option><?php if ( ! is_wp_error( $all_categories ) ) : foreach ( $all_categories as $category ) : ?><option value="<?php echo esc_attr( $category->slug ); ?>" <?php selected( $category_slug, $category->slug ); ?>><?php echo esc_html( $category->name ); ?></option><?php endforeach; endif; ?></select><input type="submit" value="Search"></form><div class="resource-stats"><div class="resource-stat"><strong><?php echo esc_html( number_format_i18n( $total_downloads ) ); ?>+</strong><span class="muted">Downloads</span></div><div class="resource-stat"><strong><?php echo esc_html( $query->found_posts ); ?>+</strong><span class="muted">Resources</span></div><div class="resource-stat"><strong><?php echo esc_html( $category_count ); ?>+</strong><span class="muted">Categories</span></div></div></div></section><section><div class="page-heading"><div><p class="eyebrow">BROWSE BY CATEGORY</p><h2>Find what you need</h2></div></div><div class="resource-categories"><?php $categories = get_terms( array( 'taxonomy' => 'resource_category', 'hide_empty' => false, 'number' => 5 ) ); if ( ! is_wp_error( $categories ) ) : foreach ( $categories as $category ) : ?><a class="resource-card" href="<?php echo esc_url( get_term_link( $category ) ); ?>"><h3><?php echo esc_html( $category->name ); ?></h3><p><?php echo esc_html( $category->count ); ?> resources</p></a><?php endforeach; endif; ?></div></section><section style="margin-top:48px"><div class="page-heading"><div><p class="eyebrow">POPULAR RESOURCES</p><h2>Practical tools for your next move</h2></div></div><div class="resource-grid"><?php if ( $query->have_posts() ) : while ( $query->have_posts() ) : $query->the_post(); ?><article class="resource-card"><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><p><?php echo esc_html( wp_trim_words( get_the_excerpt(), 18 ) ); ?></p><p class="muted resource-downloads"><?php echo esc_html( number_format_i18n( (int) get_post_meta( get_the_ID(), '_staffswap_download_count', true ) ) ); ?> downloads</p><a class="resource-link" href="<?php the_permalink(); ?>">View resource <span aria-hidden="true">&#8594;</span></a></article><?php endwhile; wp_reset_postdata(); else : ?><div class="panel"><h2>No resources found</h2><p class="muted">Try another search term.</p></div><?php endif; ?></div></section>
<?php return ob_get_clean(); }
add_shortcode( 'staffswap_resources', 'staffswap_resources_shortcode' );

function staffswap_resource_download_url( $resource_id ) { return wp_nonce_url( add_query_arg( array( 'action' => 'staffswap_download_resource', 'resource_id' => absint( $resource_id ) ), admin_url( 'admin-post.php' ) ), 'staffswap_download_' . absint( $resource_id ) ); }
function staffswap_download_resource() { $resource_id = absint( $_GET['resource_id'] ?? 0 ); if ( ! $resource_id || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['_wpnonce'] ?? '' ) ), 'staffswap_download_' . $resource_id ) ) { wp_die( 'Invalid resource request.' ); } if ( 'staff_resource' !== get_post_type( $resource_id ) ) { wp_die( 'Resource not found.' ); } $count = (int) get_post_meta( $resource_id, '_staffswap_download_count', true ); update_post_meta( $resource_id, '_staffswap_download_count', $count + 1 ); $file = get_post_meta( $resource_id, '_staffswap_resource_file', true ); wp_safe_redirect( $file ? esc_url_raw( $file ) : get_permalink( $resource_id ) ); exit; }
add_action( 'admin_post_staffswap_download_resource', 'staffswap_download_resource' ); add_action( 'admin_post_nopriv_staffswap_download_resource', 'staffswap_download_resource' );
function staffswap_resource_download_shortcode( $atts ) { $atts = shortcode_atts( array( 'id' => get_the_ID(), 'label' => 'Download resource' ), $atts, 'staffswap_resource_download' ); return '<a class="button button--primary" href="' . esc_url( staffswap_resource_download_url( $atts['id'] ) ) . '">' . esc_html( $atts['label'] ) . '</a>'; }
add_shortcode( 'staffswap_resource_download', 'staffswap_resource_download_shortcode' );